---
title: "US Metro Matching Tool"
output: 
  flexdashboard::flex_dashboard:
    source: embed
    smart: false
runtime: shiny
---


```{r global, include=FALSE}

# data and libraries for shiny widgets

library( flexdashboard )
library( tidyverse )
library( shiny )
library( knitr )
library( rsconnect )

```





US Metro Matching Tool - NMTC Example (Start here)
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

# Radio button to choose city

radioButtons( "demo.image", 
              label = h3("Cities"),
              choices = list( "Phoenix, AZ" = "phoenix.png" , 
                              "Boulder, CO" = "boulder.png", 
                              "New Orleans, LA" = "new-orleans.png", 
                              "Reno, NV" = "reno.png", 
                              "New York, NY" = "new-york.png" ), 
              selected = "new-york.png" )


```

Outputs
-------------------------------------

### Neighborhood Matches by Census Data 


```{r, eval=F}
# DEVELOPMENT CODE
# TEST WIDGET INPUTS 
renderPrint({ input$demo.image  })  

get.image <- reactive({ input$demo.image })
renderPrint({ get.image() })
```




```{r, eval=F}
# static version
renderImage({
    list( src = "new-york.png" )
  }, deleteFile=FALSE )
```

```{r}
# dynamic version linked to widget

get.image <- reactive({ input$demo.image })

renderImage({
    list( src = get.image() )
  }, deleteFile=FALSE )
```


```{r, eval=F}
# EXAMPLE WHEN IMAGES IN THEIR OWN FOLDER

# Use an existing image, and don't delete the image after sending it
# NOTE: Image is in the subdirectory called 'images/'
# when input$n is 1 filename is ./images/image1.jpeg

renderImage({
  
    # When input$n is 1, 
    filename <- normalizePath(file.path('./images',
                              paste('image', input$n, '.jpeg', sep='')))

    # Return a list containing the filename
    list(src = filename)
    
}, deleteFile = FALSE)

```



```{r, eval=F}

#Load cached NMTC data

## STEP 01

#Load a catalog of URLs of dorling cartograms for each CBSA metro area in the US. 

load_crosswalk <- function( )
{
   dorlings.url <- "https://raw.githubusercontent.com/meliapetersen/matching-project/master/data/cbsa-names-and-shapefiles.csv"
   dorlings.catalog <- read.csv( dorlings.url )
   return( dorlings.catalog )
}


dorlings.catalog <- load_crosswalk()


# Load a dorling cartogram for one metro area: 

get_dorling <- function( cbsa, dorlings.catalog=NULL, mapit=FALSE )
{

   if( is.null(dorlings.catalog) ){ dorlings.catalog <- load_crosswalk() }


   file.name <- dorlings.catalog$shapefile[ dorlings.catalog$cbsa == cbsa ]
 

   base.url <- "https://raw.githubusercontent.com/DS4PS/usa-dorling-shapefiles/master/maps/metros-dorling/"

   full.url <- paste0( base.url, file.name )

   map <- geojsonio::geojson_read( x=full.url,  what="sp" )

   if( mapit ){ plot( map ) }

   return( map )
   
}


# Test the function with New Orleans data: 



## STEP 02

# Load the New Market Tax Credit treatment data: 


df.treatment <- read.csv("rodeod-treatment-data.csv")




#Add the treatment data to the dorling spatial object: 

add_treatment <- function( df.treatment, dorling.object )
{

  # merge leftjoin dorling object and treatment data
  dorling.object <- merge( dorling.object, df.treatment, by.x="GEOID", by.y="id2", all.x=TRUE )


  # create treatment variable 
  treatment <- dorling.object$treatment 
  
  # omit NAs
  treatment[ is.na(treatment) ] <- 0
  
  #add treatment variable back into df
  dorling.object$treatment <- treatment
 

  return( dorling.object )
}

new.orleans.cbsa.code <- 35380
new.orleans <- get_dorling( cbsa=new.orleans.cbsa.code )
new.orleans <- as.data.frame(new.orleans)

# new.orleans <- add_treatment( df.treatment, dorling.object=dorlings.catalog ) 

# nmtc.treated <- add_treatment( ) need to create the object to run through the output 
  # will be replaced by "value" in the output widget 

#nmtc.data <- add_treatment( df.treatment, dorling.object=dorlings.catalog ) 
 
```






Program Data Upload 
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

# Run button (Run Default - NMTC data)
actionButton("run.default", label = "Run Default - NMTC data")


# File upload (User data)
fileInput("file.upload", label = h3("Upload Program Data"))


# Run button (User data)
actionButton("run.user.program", label = "Run - Program Data")


```

   
Outputs
-------------------------------------

### 


```{r}

# Run button pseudocode 
function(input, output) {

  # You can access the value of the widget with input$action, e.g.
  output$new.orleans <- renderPrint({ input$run.default })

}

#rmarkdown::paged_table(  head(df.treatment) )

#NMTC data headed


# File upload pseudocode
function(input, output) {

  # You can access the value of the widget with input$file, e.g.
  output$value <- renderPrint({
    str(input$file.upload)
  })

}
# Run button pseudocode 
function(input, output) {

  # You can access the value of the widget with input$action, e.g.
  output$value <- renderPrint({ input$run.user.program })

}

# User program data headed 
```   

