---
title: "US Metro Matching Tool"
output: 
  flexdashboard::flex_dashboard:
    source: embed
    smart: false
runtime: shiny
---


```{r global, include=FALSE}
# data and libraries 

##Example of what to put here below 

library( flexdashboard )
library( tidyverse )
library( ggmap )
library( leaflet )
library( viridis )
library( shiny )
library( DT )
library( pander )
library( knitr )
library( rsconnect )

URL <- "https://github.com/DS4PS/Data-Science-Class/blob/master/DATA/TempeTrafficAccidents.rds?raw=true"

```



US Metro Matching Tool - NMTC Example (Start here)
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

#Demographic checkbox  - need to change days to census variables 

checkboxGroupInput("days", label = h3("Day of Week"), 
    choices = list("Monday"    = "Mon", 
                   "Tuesday"   = "Tue", 
                   "Wednesday" = "Wed", 
                   "Thursday"  = "Thu",
                   "Friday"    = "Fri",
                   "Saturday"  = "Sat",
                   "Sunday"    = "Sun" ),
    selected = c("Fri","Sat","Sun"))

# City dropdown menu pseudocode 
selectInput(inputId, label, choices, selected = NULL, multiple = FALSE, selectize = TRUE)

# Run button pseudocode 
actionButton(inputId, label, icon = NULL)
```

   
Outputs
-------------------------------------

### Neighborhood Matches by Census Data 


```{r}

#render 5 chosen shapefiles 

#below example from previous project 
renderLeaflet({
  
  days.of.week <- input$days    # vector will all checked values
  start.time <- input$hour[1]   # sliderInput lower value
  end.time  <-  input$hour[2] 
  
  d2 <-
    dat %>%
    filter( day %in% input$days, 
            hour >= start.time & hour <= end.time )
  
  d2$col.vec <- ifelse( d2$nohurt, "gray20", ifelse(d2$inj, "steelblue", "darkorange") )              
    
  point.size <- d2$Totalinjuries + d2$Totalfatalities

  crash.details <- paste0( "Time: ", d2$DateTime, "<br>",
                     "Total Fatalities: ", d2$Totalfatalities, "<br>",
                     "Total Injuries: ", d2$Totalinjuries, "<br>",
                     "Collision type: ", d2$Collisionmanner)
  
  tempe <- leaflet( ) %>% 
              addProviderTiles( "CartoDB.Positron" )  %>%
              setView( lng=-111.9278, lat=33.39951, zoom=13 )
  
  
  addCircles( tempe, lng=d2$Longitude, lat=d2$Latitude,
              fillColor=d2$col.vec, fillOpacity=0.5, 
              stroke=F, radius=50*(1+0.33*point.size),
              popup=crash.details )


})


#City dropdown menu pseudocode 
function(input, output) {

  # You can access the value of the widget with input$select, e.g.
  output$value <- renderPrint({ input$select })

}

# Run button pseudocode 
function(input, output) {

  # You can access the value of the widget with input$action, e.g.
  output$value <- renderPrint({ input$action })

}
```   

Program Data Upload 
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

# File upload pseudocode 
fileInput(inputId, label, multiple = FALSE, accept = NULL)

# Run button pseudocode 
actionButton(inputId, label, icon = NULL)

#Head data to show merged and cleaned 

```

   
Outputs
-------------------------------------

### 


```{r}

# File upload pseudocode
function(input, output) {

  # You can access the value of the widget with input$file, e.g.
  output$value <- renderPrint({
    str(input$file)
  })

}

# Run button pseudocode 
function(input, output) {

  # You can access the value of the widget with input$action, e.g.
  output$value <- renderPrint({ input$action })

}

# data headed 
```   

Matching Analysis
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}

# Checkboses changed for census variables 
checkboxGroupInput("days", label = h3("Day of Week"), 
    choices = list("Monday"    = "Mon", 
                   "Tuesday"   = "Tue", 
                   "Wednesday" = "Wed", 
                   "Thursday"  = "Thu",
                   "Friday"    = "Fri",
                   "Saturday"  = "Sat",
                   "Sunday"    = "Sun" ),
    selected = c("Fri","Sat","Sun"))


 
# Run button pseudocode 
actionButton(inputId, label, icon = NULL)

# Download CSV button pseudocode 
actionButton(inputId, label, icon = NULL)

```

   
Outputs
-------------------------------------

### 


```{r}

# matched data analysis 

# Run button pseudocode 
function(input, output) {

  # You can access the value of the widget with input$action, e.g.
  output$value <- renderPrint({ input$action })

}

# Download CSV button pseudocode 
function(input, output) {

  # You can access the value of the widget with input$action, e.g.
  output$value <- renderPrint({ input$action })

}
```   

Maps Matched by Census Tract
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}
#dropdown for metro areas that matches were analyzed by 

# City dropdown menu pseudocode 
selectInput(inputId, label, choices, selected = NULL, multiple = FALSE, selectize = TRUE)

# Run button pseudocode 
actionButton(inputId, label, icon = NULL)

##If everything is perfect, create checkbox option for census variable to create cloropleth map for comparison 
    ## Will be radio button to decide between cloropleth map or matches map 
    ## Also option to show maps side by side for analysis 

# download shapefile "data" button pseudocode 
actionButton(inputId, label, icon = NULL)

```

   
Outputs
-------------------------------------

### 


```{r}

#City dropdown menu pseudocode 

function(input, output) {

  # You can access the value of the widget with input$select, e.g.
  output$value <- renderPrint({ input$select })

}

# Run button pseudocode 
function(input, output) {

  # You can access the value of the widget with input$action, e.g.
  output$value <- renderPrint({ input$action })

}

# Shapefile matched map shown here 
# (render shapefile)

# downloadable html shapefile catalog
# Run button pseudocode 
function(input, output) {

  # You can access the value of the widget with input$action, e.g.
  output$value <- renderPrint({ input$action })

}

```   


Executive Summary 
===================================== 



Row 
-------------------------------------

### About this Dashboard 

Data from: XXX

This dashboard uses... 

### Dashboard Author

Melia Petersen, Melia.Petersen@asu.edu, Tempe, AZ
Jaesa Rogers, Jaesa.Rogers@asu.edu, Tempe, AZ 

Row
-------------------------------------

DATA DICTIONARY 


```{r}
URL.dd <- "https://raw.githubusercontent.com/DS4PS/cpp-526-fall-2019/master/labs/final-project/TempeTrafficAccidentsDataDictionary.csv"
data.dictionary <- read.csv( URL.dd, stringsAsFactors=F )

data.dictionary$description <- stringi::stri_trans_general( data.dictionary$description, "latin-ascii" )
data.dictionary %>%
  select( column, description ) %>%
  pander( )
```



Data
=====================================  

```{r}
# library( DT )

these.buttons <- c( 'copy', 'csv', 'pdf', 'print' )

renderDataTable({
  datatable(dat[1:100,], filter='bottom', rownames=FALSE, 
           #options=list( pageLength=5, autoWidth=TRUE ),
           fillContainer=TRUE, 
           style="bootstrap",
           class='table-condensed table-striped',
           extensions = 'Buttons', 
           options=list( dom='Bfrtip', 
                         buttons=these.buttons  ) )
})
```
