---
title: "US Metro Matching Tool"
output: 
  flexdashboard::flex_dashboard:
    source: embed
    smart: false
runtime: shiny
---


```{r global, include=FALSE}

# data and libraries for shiny widgets

library( flexdashboard )
library( tidyverse )
library( shiny )
library( knitr )
library( rsconnect )
library(pander)
library( DT )

```

```{r, eval=F}

#Load cached NMTC data

## STEP 01

#Load a catalog of URLs of dorling cartograms for each CBSA metro area in the US. 

load_crosswalk <- function( )
{
   dorlings.url <- "https://raw.githubusercontent.com/meliapetersen/matching-project/master/data/cbsa-names-and-shapefiles.csv"
   dorlings.catalog <- read.csv( dorlings.url )
   return( dorlings.catalog )
}


dorlings.catalog <- load_crosswalk()


# Load a dorling cartogram for one metro area: 

get_dorling <- function( cbsa, dorlings.catalog=NULL, mapit=FALSE )
{

   if( is.null(dorlings.catalog) ){ dorlings.catalog <- load_crosswalk() }


   file.name <- dorlings.catalog$shapefile[ dorlings.catalog$cbsa == cbsa ]
 

   base.url <- "https://raw.githubusercontent.com/DS4PS/usa-dorling-shapefiles/master/maps/metros-dorling/"

   full.url <- paste0( base.url, file.name )

   map <- geojsonio::geojson_read( x=full.url,  what="sp" )

   if( mapit ){ plot( map ) }

   return( map )
   
}


# Test the function with New Orleans data: 



## STEP 02

# Load the New Market Tax Credit treatment data: 


df.treatment <- read.csv("rodeod-treatment-data.csv")




#Add the treatment data to the dorling spatial object: 

add_treatment <- function( df.treatment, dorling.object )
{

  # merge leftjoin dorling object and treatment data
  dorling.object <- merge( dorling.object, df.treatment, by.x="GEOID", by.y="id2", all.x=TRUE )


  # create treatment variable 
  treatment <- dorling.object$treatment 
  
  # omit NAs
  treatment[ is.na(treatment) ] <- 0
  
  #add treatment variable back into df
  dorling.object$treatment <- treatment
 

  return( dorling.object )
}

new.orleans.cbsa.code <- 35380
new.orleans <- get_dorling( cbsa=new.orleans.cbsa.code )
new.orleans <- as.data.frame(new.orleans)

# new.orleans <- add_treatment( df.treatment, dorling.object=dorlings.catalog ) 

# nmtc.treated <- add_treatment( ) need to create the object to run through the output 
  # will be replaced by "value" in the output widget 

#nmtc.data <- add_treatment( df.treatment, dorling.object=dorlings.catalog ) 
 
```






Program Data Upload 
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}


# File upload (User data)
fileInput("upload", label = h3("Upload Program Data"))


# Run button (User data)
actionButton("run.user.program", label = "Run - Program Data")


```



   
Outputs
-------------------------------------

### 

```{r}


#rmarkdown::paged_table(  head(df.treatment) )



# File upload pseudocode
get_user_data <- reactive({
  
  if(is.null(input$upload))
    {head(new.orleans)}
  head(input$upload)

 
  })

user.dat <- get_user_dat()



# Run button pseudocode 

observeEvent(input$run.user.program, 
          
{  
   user.dat <- get_user_dat()
   d2 <- merge( x=user.dat, y=census.dat, by.x=GEOID , by.y=tractid )
  
   
   # create treatment variable 
  treatment <- d2$treatment 
  
  # omit NAs
  treatment[ is.na(treatment) ] <- 0
  
  #add treatment variable back into df
  d2t$treatment <- treatment
 

  return( d2 )
}
 )
  

  


# User program data headed 
```   
Row
-------------------------------------
```{r}
# will be replaced with data from chosen option, currenly using preloaded data "iris" 

these.buttons <- c( 'copy', 'csv', 'pdf', 'print' )

renderDataTable({
  datatable( iris[1:100,], filter='bottom', rownames=FALSE, 
           #options=list( pageLength=5, autoWidth=TRUE ),
           fillContainer=TRUE, 
           style="bootstrap",
           class='table-condensed table-striped',
           extensions = 'Buttons', 
           options=list( dom='Bfrtip', 
                         buttons=these.buttons  ) )
})
```
