---
title: "Metro-Matching"
author: "Jaesa Rogers"
date: "8/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning=F )
```


```{r}
# need this installed to use
# genetic matching option in MatchIt
# install.packages("rgenoud")

# load package 
library( MatchIt )
library( here )
library( dplyr )
```

```{r}
#load LTDB data
d1 <- readRDS(here ( "data/data-rodeo/LTDB-2000.rds" ))
d2 <- readRDS(here ( "data/data-rodeo/LTDB-2010.rds" ))
md <- readRDS(here ( "data/data-rodeo/LTDB-META-DATA.rds" ))

#clean data 
d1 <- select( d1, - year )
d2 <- select( d2, - year )

d <- merge( d1, d2, by="tractid" )
d <- merge( d, md, by="tractid" )

#load NMTC data 
URL1 <- "https://raw.githubusercontent.com/DS4PS/cpp-528-spr-2020/master/labs/data/raw/NMTC/nmtc-sheet-01.csv"
nmtc <- read.csv( URL1, stringsAsFactors=F )

# remove anything not a number from the string
d$id2 <- gsub( "[^0-9]", "", d$tractid )

# fix IDs so they are match
d$id2 <- as.numeric( d$id2 )

# need to convert from currency to numeric
# current format: 
# head( nmtc$QLICI.Amount )
# [1] "$300,000.00 "   "$1,008,750.00 " "$977,000.00 "

# remove dollar sign and commas
nmtc$amount <- gsub( "[,$]", "", nmtc$QLICI.Amount )

# head(  nmtc$amount  )
# "300000.00 "  "1008750.00 " "977000.00 "

# convert characters to numeric 
nmtc$amount <- as.numeric( nmtc$amount ) %>% round(0)

# head(  nmtc$amount  )
# [1]  300000 1008750  977000

nmtc.dollars <- 
  nmtc %>% 
  filter( Origination.Year >= 2000 & Origination.Year <= 2010 ) %>%
  group_by( X2010.Census.Tract ) %>% 
  summarize( num.nmtc=n(), nmtc.total = sum( amount, na.rm=T ) )

d <- merge( d, nmtc.dollars, by.x="id2", by.y="X2010.Census.Tract", all.x=T )

# recode tracts that had no grants from NA to 0
d$num.nmtc[ is.na(d$num.nmtc) ] <- 0
d$nmtc.total[ is.na(d$nmtc.total) ] <- 0

#remove rural districts 
d <- filter( d, urban == "urban" )


```

### Create data frame for matching

```{r}

# create treatment variable
treatment <- ifelse(d$nmtc.total>0, 1, 0)

# add to dataframe

d$treatment <- treatment

```



```{r}
# match nmtc as treatment (census tracts that recieved nmtc funding vs those that didn't)
# and seek balance on other SES characteristics 

## immigrants, high school education, home ownership, pop density (cpp 528 lab), tenure in the neighborhood

df <- 
  d %>% 
  select( cbsa, id2, treatment, rent00, hinc00, pnhwht12, pnhblk12, phisp12, 
              ppov12, punemp12,
              hinc12, hincb12, hincw12, 
              phs12, pcol12,
              pown12, mhmval12 ) %>% 
 filter( treatment %in% c( 1,0 ) ) %>% 
 mutate( Treated = as.numeric( treatment == 1 ), 
           Control =  as.numeric( treatment == 0 ))

# drop rows with missing values

nrow( df )
df2 <- na.omit( df )
nrow( df2 )


# "treated" group is white
# comparison set is minority communities
```


### matchit function 


**NOTE** the long output printed while the algorithm runs. Add code chunk option

results 


```{r}

build_matchit_metros <- function( cbsa, include.plot=TRUE )

  {

	these.counties  <- df2$cbsa 
	these.fips <- df2$id2[ these.counties ]
	these.fips <- na.omit( these.fips )

	state.fips <- substr( these.fips, 1, 2 )
	county.fips <- substr( these.fips, 3, 5 )
	
	# test genetic search method
# is time-intensive so test with a sample

# set seeds if you want to reproduce the 
# exact result in the future
set.seed( seed=1234 )

# create sample set for cities with high NMTC funding: New Orleans
df3 <- df2  %>%  filter(cbsa %in% 35380)

row.names(df3) <- df3$id2    
df3 <- na.omit( df3 )

# df3$cbsa.f <- factor(df3$cbsa)      
                 
table( df3$treatment )


m5 <- matchit( treatment ~ hinc12 + pcol12 + pnhwht12, 
               method="genetic", discard="both", reestimate=TRUE, 
               replace=FALSE, caliper=.25, data = df3 )

	}


```

# Run matchit_metro function

```{r}
build_matchit_metros()
```

# Build dataframe vectors function

```{r}
# match matrix is the length of the original treated groups
# IDs are rows of the original dataset

vectors_function <- function()

{

matches <- data.frame( treatment.group.id=row.names( m5$match.matrix), 
                       control.group.id=m5$match.matrix )

these.na <- is.na(matches$control.group.id)

id.all.treated <- matches$treatment.group.id 
id.treated.matched <- matches$treatment.group.id[!these.na]
id.treated.unmatched <- matches$treatment.group.id[these.na]
id.control.matched <- na.omit(matches$control.group.id)
id.control.unmatched <- df3$id2 [ !(df3$id2 %in% id.all.treated | df3$id2 %in% id.control.matched)]

df.x <- data.frame(Fips = id.treated.matched, group = "treated", matched = TRUE)
df.x

# rowbind

matches <- na.omit(matches)

sum(is.na(matches$control.group.id))


m5$nn

# all treated cases in dataset:
length( m5$match.matrix )

# treated cases that were matched: 
sum( ! is.na(m5$match.matrix) )

### Extract balanced dataset 


new.dat <- match.data( m5 )
dim( new.dat ) # 2 x number in matched treatment group




### Create Treatment and Control vectors


# id.all.treated <- matches$treatment.group.id 
# id.treated.matched <- matches$treatment.group.id[!these.na]
# id.treated.unmatched <- matches$treatment.group.id[these.na]
# id.control.matched <- na.omit(matches$control.group.id)
# id.control.unmatched <- df3$id2 [ !(df3$id2 %in% id.all.treated | df3$id2 %in% id.control.matched)]

treated.matched <- na.omit(id.treated.matched) %>% as.numeric
control.matched <- na.omit(id.control.matched) %>% as.numeric

treated.unmatched <- na.omit(id.treated.unmatched)  %>% as.numeric
control.unmatched <- na.omit(id.control.unmatched)  %>% as.numeric
}
```

```{r}
vectors_function()
```


### Load dorling


```{r}
library( geojsonio )
library( sp )

github.url <- "https://github.com/DS4PS/usa-dorling-shapefiles/raw/master/maps/metros-dorling/new-orleans-metairie-kenner-la-dorling-v2.geojson"
no <- geojson_read( x=github.url,  what="sp" )
 


plot( no )


```



### Create color vectors based on matches 

```{r, fig.height=10, fig.width=20}



color.vector <- rep( "gray", nrow(df3) )
color.vector[ df3$id2 %in% control.matched ] <- "blue"
color.vector[ df3$id2 %in% treated.matched ] <- "darkred"
color.vector[ df3$id2 %in% treated.unmatched ] <- adjustcolor( "darkred", alpha.f = 0.4 )


border.color <- rep( "gray40", nrow(df3) )
border.color [ df3$id2 %in% treated.unmatched ] <- "darkred"


par(mar=c(0,0,0,0))

plot(no, col= color.vector, border=border.color)



```