---
title: "metro-matching-loop"
author: "Jaesa Rogers"
date: "9/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning=F )
```


```{r}
# need this installed to use
# genetic matching option in MatchIt
# install.packages("rgenoud")

# load package 
library( MatchIt )
library( here )
library( dplyr )

library( geojsonio )
library( sp )
```


## FIRST FUNCTION

```{r}

  ### dorling function

load_crosswalk <- function( )
{
   dorlings.url <- "https://raw.githubusercontent.com/meliapetersen/matching-project/master/data/cbsa-names-and-shapefiles.csv"
   dorlings.catalog <- read.csv( dorlings.url )
   return( dorlings.catalog )
}

dorlings.catalog <- load_crosswalk()



get_dorling <- function( cbsa, dorlings.catalog=NULL )
{

   if( is.null(dorlings.catalog) ){ dorlings.catalog <- load_crosswalk() }


   file.name <- dorlings.catalog$shapefile[ dorlings.catalog$cbsa == cbsa ]
 

   base.url <- "https://raw.githubusercontent.com/DS4PS/usa-dorling-shapefiles/master/maps/metros-dorling/"

   full.url <- paste0( base.url, file.name )

   map <- geojsonio::geojson_read( x=full.url,  what="sp" )

   plot( map )

   return( map )
   
}

  
metro.cbsa <- 10580

dorling.object <- get_dorling( cbsa=metro.cbsa )


```

## SECOND FUNCTION

```{r}

### Rodeo data function 

df.treatment <- read.csv("rodeod-treatment-data.csv")
# df.census <- dorling.object@data

do.original <- dorling.object
dorling.object <- do.original


add_treatment <- function( df.treatment, dorling.object )
{

  # merge leftjoin
  dorling.object <- merge( dorling.object, df.treatment, by.x="GEOID", by.y="id2", all.x=TRUE )


  # dorling.object <- df2
  # x <- c( 1, NA, NA, 1, NA, NA )
  # 
  # omit NAs
  treatment <- dorling.object$treatment 
  treatment[ is.na(treatment) ] <- 0
  dorling.object$treatment <- treatment
 
  # row.names(df.rodeo.metro) <- df.rodeo.metro$id2    
  # df.rodeo.metro <- na.omit( df.rodeo.metro )

  return( dorling.object )
}

dorling.object <- add_treatment( df.treatment, dorling.object ) 
table( dorling.object$treatment, useNA="ifany" )
  
```


```{r}
head(df.treatment)
```


```{r}
head(dorling.object)

```
## SECOND FUNCTION

### matchit function 
```{r}

fo <- as.formula( "treatment ~ own00" )
df <- as.data.frame( dorling.object )

build_matchit_metros <- function( fo, df )
{
   matchit.object <- NULL

   # find matches in dataframe based on Household income, college education, and whiteness 
   try(   
      matchit.object <- matchit( fo, 
                        method="genetic", discard="both", reestimate=TRUE,
                        replace=FALSE, caliper=.25, data = df )
   )

   return( matchit.object )

}

mo <- build_matchit_metros( fo, df )

```

```{r}

matchit.object <- build_matchit_metros( dorling.object ) 
```


## THIRD FUNCTION

### Build dataframe vectors function

```{r}
# match matrix is the length of the original treated groups
# IDs are rows of the original dataset

build_colored_map <- function( matchit.object )
{

  matches <- data.frame( treatment.group.id=row.names( matchit.object$match.matrix), 
                       control.group.id=matchit.object$match.matrix )

  these.na <- is.na(matches$control.group.id)

  id.all.treated <- matches$treatment.group.id 
  id.treated.matched <- matches$treatment.group.id[!these.na]
  id.treated.unmatched <- matches$treatment.group.id[these.na]
  id.control.matched <- na.omit(matches$control.group.id)
  id.control.unmatched <- rodeo.metro.i$id2 [ !(rodeo.metro.i$id2 %in% id.all.treated | rodeo.metro.i$id2 %in% id.control.matched)]

# df.x <- data.frame(Fips = id.treated.matched, group = "treated", matched = TRUE)
# df.x

# rowbind

matches <- na.omit(matches)

sum(is.na(matches$control.group.id))


matchit.object$nn

# all treated cases in dataset:
length( matchit.object$match.matrix )

# treated cases that were matched: 
sum( ! is.na(matchit.object$match.matrix) )

### Extract balanced dataset 
new.dat <- match.data( matchit.object )
dim( new.dat ) # 2 x number in matched treatment group


### Create Treatment and Control vectors

treated.matched <- na.omit(id.treated.matched) %>% as.numeric
control.matched <- na.omit(id.control.matched) %>% as.numeric

treated.unmatched <- na.omit(id.treated.unmatched)  %>% as.numeric
control.unmatched <- na.omit(id.control.unmatched)  %>% as.numeric

### Create color vectors based on matches

color.vector <- rep( "gray", nrow(rodeo.metro.i) )
color.vector[ rodeo.metro.i$id2 %in% control.matched ] <- "blue"
color.vector[ rodeo.metro.i$id2 %in% treated.matched ] <- "darkred"
color.vector[ rodeo.metro.i$id2 %in% treated.unmatched ] <- adjustcolor( "darkred", alpha.f = 0.4 )

border.color <- rep( "gray40", nrow(rodeo.metro.i) )
border.color [ rodeo.metro.i$id2 %in% treated.unmatched ] <- "darkred"

lat <- rnorm(1000)
quantile( lat, c( 0.25, 0.75 ) )

# in the plot function
xlim=quantile( lat, c(0.25,0.75) )

par(mar=c(0,0,0,0))

plot(dorling.object, col= color.vector, border=border.color)

}

```

```{r}
colored.map <- build_colored_map()
```

## Create loop for all CBSAs 

```{r}

# prep data for the loop? how do we test? 

dorlings.catalog <- load_crosswalk()

cbsa.list <- unique( dorlings.catalog$cbsa )

for( i in cbsa.list )
{
   dorling.object.i <- get_dorling( cbsa=i, dorlings.catalog )
   dorling.object.i <- add_treatment( df.treatment, dorling.object.i )
   rodeo.data.i <- dorling.object.i@data
   fo <- as.formula( "treatment ~ hinc12" )
   matchit.model <- build_matchit_metros( fo=fo, rodeo.df=rodeo.data.i )
   build_colored_map( matchit.object=matchit.model )

}


```




